import share from "../../assets/images/share.png"
import heart from "../../assets/images/heart.png"
import arrowLeft from "../../assets/images/arrowLeft.svg"
import people from "../../assets/images/people.png"
import pad from "../../assets/images/pad.png"
import note from "../../assets/images/note.png"
import calender from "../../assets/images/calender.png"
import house from "../../assets/images/house.png"
import tag from "../../assets/images/tag.svg"
import userCancel from "../../assets/images/userCancel.svg"
import userCheck from "../../assets/images/userCheck.svg"
import userSpeak from "../../assets/images/userSpeak.svg"
import mail from "../../assets/images/mail.svg"
import arrowDown from "../../assets/images/arrowDown.svg"
import settings from "../../assets/images/settings.svg"
import play from "../../assets/images/play.svg"
import pad2 from "../../assets/images/pad2.svg"


export {share, calender, people, pad, note, arrowLeft, heart, house, tag, mail, userCancel, userCheck, userSpeak, arrowDown, settings, play, pad2}